### ISSUE TITLE
MSYS2 installer fails with: "MSYS2 seems to be unavailable"

### ISSUE THREAD

**Issue by ahirschberg** [oneclick/rubyinstaller#369]
I'm running into an issue with the MSYS2 installer, running on a Windows .NET Core (v4.6) box.

Output of `ridk version`:
```
C:\tools\ruby24>C:\tools\ruby24\bin\ridk.cmd version
---
ruby:
  path: C:/tools/ruby24
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-2
  git_commit: a2667ee
```

Output of ridk install:
```
C:\tools\ruby24>C:\tools\ruby24\bin\ridk.cmd install
 _____       _           _____           _        _ _         ___
|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

   1 - MSYS2 base installation
   2 - MSYS2 system update
   3 - MSYS2 and MINGW development toolchain

Which components shall be installed? If unsure press ENTER [1,2,3] 1

MSYS2 seems to be unavailable
Verify integrity of msys2-x86_64-20161025.exe ... OK
Run the MSYS2 installer ...
> C:\Users\ADMINI~1\AppData\Local\Temp\2/msys2-x86_64-20161025.exe
 Failed
Installation failed: MSYS2 installer failed
```

The install is failing, so I can't resolve some dependencies:
```
C:\tools\ruby24\alex>..\bin\gem install libyajl2
MSYS2 could not be found. Please run 'ridk install'
or download and install MSYS2 manually from https://msys2.github.io/
```
